### ISSUE TITLE
No /schedule command found

### ISSUE THREAD

**Issue by ReasonablySelenium** [gr2m/merge-schedule-action#14]
I'm getting this error whenever I try to schedule a blog post in the future on GitHub Actions:
> No /schedule command found

**Comment by ReasonablySelenium** [comment]
Alright so apparently you the only thing that can be put in the Pull Request is the scheduling command. Any other text has to be deleted before this GitHub Action will work.

**Comment by gr2m** [comment]
The `/schedule` command must be set at the very end of the pull request description if I recall correctly.

I'd happily accept a pull request to improve that behavior, as long as it includes tests

**Comment by nazariidmytrakh** [comment]
seems like "/schedule..." also should start at the new line

it works:
```
Automatically generated by Netlify CMS
/schedule Thu, 27 May 2021 10:35:00 GMT
```

it doesn't work:
```
Automatically generated by Netlify CMS /schedule Thu, 27 May 2021 10:35:00 GMT
```

**Comment by gr2m** [comment]
correct
