### ISSUE TITLE
How can I schedule different PR on same day but with different time ? 

### ISSUE THREAD

**Issue by hmble** [gr2m/merge-schedule-action#15]
Thanks a lot for this github action. 🥳
I want to schedule more than one PR but with different time on day.
For example `/schedule 2020-08-15T13:00Z`
Is this possible ?

**Comment by hmble** [comment]
According to [css-tricks](https://css-tricks.com/everything-you-need-to-know-about-date-in-javascript/) article 
```js
// ISO 8601 Extended format
`YYYY-MM-DDTHH:mm:ss.sssZ`
```
is a valid Date string. Fortunately this works :tada: on my own webiste https://github.com/hmble/deploy-vercel/pull/2/

**Comment by gr2m** [comment]
The date string is passed into the `new Date()` constructor, so anything that is supported by that will work :)
