### ISSUE TITLE
Add ability to preform a squash commit

### ISSUE THREAD

**Issue by cbetta** [gr2m/merge-schedule-action#25]
We generally use squash commits in our project. Would this be possible to add to this action? Currently I get an error when merge commits have been disabled on the project.

**Comment by gr2m** [comment]
Yes, sure! 

The code change would need to happen here:
https://github.com/gr2m/merge-schedule-action/blob/03ba2b293aca4984cdb23e476edbde5a93403ee3/lib/handle_schedule.js#L55-L59

Here is the documentation for the `.pulls.merge()` method:
https://octokit.github.io/rest.js/v18#pulls-merge

You'll have to add a `with` parameter, which needs to be defined in https://github.com/gr2m/merge-schedule-action/blob/master/action.yml, compare https://github.com/octokit/request-action/blob/10560e1ee485c9f515009d937c13f1f221c64757/action.yml#L6-L13

And the documentation needs to be updated in README.md

Would you like to send a pull request? We don't have any tests yet unfortunately, but the action is simple enough, we should be fine without :D

**Comment by cbetta** [comment]
Thanks for the detailed instructions @gr2m. I made a PR with what i think is the correct changes.
