### ISSUE TITLE
Request: automatic tagging for major/minor tag

### ISSUE THREAD

**Issue by tsuyoshicho** [gr2m/merge-schedule-action#27]
Currently, tag is always vX.Y.Z.

But workflow need to wrote with v1 / v1.2 for maintenance free.

Please tag v1 and v1.0/1.1/1.2 and new tag add then moved these tags.

i.e. my created action use below:
https://github.com/tsuyoshicho/action-textlint/blob/master/.github/workflows/update_semver.yml

**Comment by gr2m** [comment]
new releases are constantly pushed to `v1.x`. If you want to pin a version, you can use any of the tags, e.g. `v1.2.4`. What else do you need?

**Comment by tsuyoshicho** [comment]
Sorry, OK I lost branch info...

These resolve problem, Thanks.
