### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/home/runner/work/_actions/gr2m/merge-schedule-action/v1.x/dist/bridge.js'

### ISSUE THREAD

**Issue by gr2m** [gr2m/merge-schedule-action#59]
seems to have been introduced since the upgrade to v16? Any idea @ruisaraiva19? Do you see the error in your repositories?

**Comment by ruisaraiva19** [comment]
Oh, I see the issue, the build script now generates multiple JS files inside the dist folder but the `@sematic-release/git` plugin is only committing the `dist/index.js` file.

I opened a [PR](https://github.com/gr2m/merge-schedule-action/pull/60) with a fix for it.
