### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by AHumanIBelieve** [gr2m/merge-schedule-action#78]
I am attempting to use merge-schedule-action to update my webcomic. However the workflow job fails. The description goes like:
`/schedule 2022-01-02`(which is it)
But I get an error when it runs the job after creating the pull request.
```
Run gr[2](https://github.com/AHumanIBelieve/ahumanibelieve.github.io/actions/runs/3817569850/jobs/6493904876#step:2:2)m/merge-schedule-action@v2
  with:
    merge_method: merge
    time_zone: UTC
    require_statuses_success: false
    automerge_fail_label: automerge-fail
  env:
    GITHUB_TOKEN: ***
Handling pull request opened for https://github.com/AHumanIBelieve/ahumanibelieve.github.io/pull/[5](https://github.com/AHumanIBelieve/ahumanibelieve.github.io/actions/runs/3817569850/jobs/6493904876#step:2:4)
Schedule date found: "2022-01-02"
Error: HttpError: Resource not accessible by integration
```
Is there something I am missing or is it just my repo? Do I need to give it permissions or something?
Link to pull request: [https://github.com/AHumanIBelieve/ahumanibelieve.github.io/pull/5](https://github.com/AHumanIBelieve/ahumanibelieve.github.io/pull/5)
Thanks for any help!

**Comment by AHumanIBelieve** [comment]
UPDATE: At the scheduled time, the job still threw the same error

**Comment by LucaNerlich** [comment]
Same error. Do we need to create a secret in our repo settings? What value does it expect?

**Comment by AHumanIBelieve** [comment]
I just reinstalled the thing with the button on the github marketplace page, and it worked. That probably set up the secret for us.

**Comment by martbhell** [comment]
Sorry for hijack.

> create a personal access token with enough rights.

What is enough rights? Is this documented somewhere?

**Comment by AHumanIBelieve** [comment]
> go to your account settings -> developer settings -> create a personal access token with enough rights.
> Go to your repo -> settings -> secrets -> actions -> "add new repo secrect". Call it "PAT" and add your token created earlier. In your yml replace `secret.GITHUB_TOKEN` with `secret.PAT`.
> 
> done
Do this, I think, @martbhell

**Comment by martbhell** [comment]
Yeah. But theres lots of rights one can add.

**Comment by martbhell** [comment]
Sorry for spam. Guess I found the missing permissions as the PR merged!

 If someone has a list of the minimum permissions needed that would be nice to reduce scope on the token :)

**Comment by j2kun** [comment]
+1 to @martbhell's comment: I would like to know what subset of permissions to configure.

**Comment by gr2m** [comment]
It should be content:write and pull_requests:write
