### ISSUE TITLE
With require_statuses_success as 'true', PRs never get merged

### ISSUE THREAD

**Issue by oliviagyg** [gr2m/merge-schedule-action#82]
The title pretty much sums it up. It seems like because the commit status is set to 'pending' when the merge is scheduled, this then leads the statuses check to always fail, as it's expecting 'success'. So despite all status checks passing, it won't get merged because the merge-schedule action itself changed the status.

**Comment by gentksb** [comment]
Do you mean that merge-schedule sets commit status as 'pending', but merge-schedule check itself as 'complete' or 'success' so it never merge PR?
I'm facing the similar issue when I set `require_statuses_success: "true"`.

**Comment by andrijasinski** [comment]
Le dot.
I am having similar issue. Action checks are green, but PR never gets merged.

**Comment by FelixMarcusMillne** [comment]
Pushed a fix for this issue as I saw it (i.e. `/commits/<commit-ref>/status` returning a combined status of `pending` when the statuses block was pending)
