### ISSUE TITLE
Merger says the date is already in the past

### ISSUE THREAD

**Issue by emma-sax4** [gr2m/merge-schedule-action#9]
I have a run here: https://github.com/emma-sax4/emma-sax4.github.io/pull/216/checks?check_run_id=680130245.

But for some reason it says the date (`2020-05-16`) is already in the past... but right now, it's 2020-05-16 UTC. Why does it think the day is in the past?

**Comment by emma-sax4** [comment]
Ah. The reason is because when you set the date, it needs to be in UTC, and then it defaults to the start of the day (not including the entire 24 hours in the day). You can pass a time in after the day to be more specific.

**Comment by gr2m** [comment]
Hmm maybe we should add support for time zones? Or at least document that the date is treated as UTC?

**Comment by emma-sax4** [comment]
I figured that it might be in UTC, but the trick was that if I put in `2020-01-01`, that means `2020-01-01 at 00:00`. So if I was actually writing my thing at 15:30 in the afternoon on the 1st of January in UTC,  then the "time has passed" even though in my brain, I thought of it as still being 2020-01-01.
